# Publicaciones libres
<!-- # Punto de partida: la investigación abierta  -->

Un agricultor hace uso de sus *herramientas, talentos y conocimientos* para aprovechar lo mejor posible las ventajas del bien común que es la tierra. Una vez que termina la temporada, el agricultor entrega la cosecha a un distribuidor que se encarga de comercializar el fruto de su trabajo y el de otros agricultores. ¿Cuánto recibe realmente el agricultor por su trabajo? *¿Cuáles son las posibilidades reales que tiene la ciudadanía de acceder al bien común de manera autónoma?*  

El problema del agricultor, el distribuidor y la ciudadanía no es una historia del pasado. El producto de un trabajo que hace uso de un bien común, y el cómo este se distribuye y retribuye dentro de la sociedad, es un tema que cada vez suscita más interés no solo en los gobiernos y la ciudadanía, sino que también en la ciencia. Esto debido a que, como el agricultor elaboró cosechas a partir de la tierra, el científico construirá evidencia nueva a partir de conocimientos previos. Ambos crean productos que son bienes esenciales para la ciudadanía a partir de bienes comunes de la humanidad. El problema para ambos está en que parte de ese quehacer ha sido privatizado, restringiendo a la ciudadanía del libre acceso a tales bienes.

Esta problemática también es extrapolable a la situación que ocurre con las patentes de vacunas y, en específico, con las patentes de las *vacunas de COVID-19*, donde gran parte de [los organismos internacionales llaman a que estas sean consideradas *bienes públicos*](https://en.unesco.org/news/unesco-calls-covid-19-vaccines-be-considered-global-public-good){target="_blank"}. Así como la privatización al acceso de un conocimiento médico produce desigualdad entre los países más y menos ricos, también el acceso al conocimiento por parte de la sociedad en general -evidencia de cómo mejorar el cumplimiento de las medidas de cuidado, por ejemplo- implicó un daño invaluable en cómo se produjo y se distribuyó la información para combatir la pandemia.

Así, a pesar de que con *la globalización y la era digital* la labor científica ha podido crear conocimientos con mayor facilidad y divulgarlos de manera inmediata, el desconocimiento y los mitos sobre las leyes que amparan la propiedad intelectual han sido el principal obstáculo para dar el paso hacia la apertura de la creación científica [@fernandez_derechos_2018]. El miedo a ser sancionado por la editorial, el temor al plagio y la pérdida de reconocimiento autoral, destacan entre las principales razones, sin mencionar el dominio que poseen las revistas científicas sobre el conocimiento que se genera y que es publicado por ellas. Dicho esto, la apuesta por destinar los esfuerzo hacia una libre circulación del conocimiento apunta a la necesidad de reapropiarse de los beneficios, resultados y saberes científicos. En este sentido, @banzato_soberania_2019 hace un llamado a los organismos de América Latina para generar espacios de evaluación y difusión que sirvan para la democratización del conocimiento, siendo esta una estrategia cultural y política que busca promover los procesos de producción y reproducción social del saber.  

La apertura de nuestras investigaciones traen más beneficios que dificultades: no solo contribuimos a nutrir el conocimiento colectivo sobre un problema, sino que incluso podemos alcanzar mejor visibilidad de nuestro trabajo científico. Por eso, en el siguiente capítulo te presentaremos aspectos que debes considerar para lograr una exitosa apertura de tus publicaciones y resultados de investigación.
